### ISSUE TITLE
Elements that are supposed to be links are not clickable and don't behave like a link

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-valery.valadzko#11]
![image](https://user-images.githubusercontent.com/710513/28169639-a90b015e-67eb-11e7-831c-562e8839a42b.png)
![image](https://user-images.githubusercontent.com/710513/28169649-b26155e6-67eb-11e7-85a3-bc7b8ad38c69.png)

**Comment by valeryvaladzko** [comment]
Fixed
would be in next commit
