### ISSUE TITLE
2.1 JS -> не очень понятный UI

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-valery.valadzko#14]
Пока не залез в код, не понял как же мне ввести массив. + непонятные кнопки Get Array и Create Array (эта видимо вообще не работает, либо я не понял как ее использовать). UI должен быть понятен настолько, чтобы не приходилось лезть в код.

**Comment by valeryvaladzko** [comment]
Добавлено описание работы с формой на странице. Будет добавлено в следующем коммите
