### ISSUE TITLE
2.1 JS - странные результаты при пустом массиве

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-valery.valadzko#15]
Я ничего не ввел и начал нажимать кнопки
![image](https://user-images.githubusercontent.com/710513/29059381-f71c65f4-7c1d-11e7-9de4-e2dbe6be0bfd.png)

**Comment by valeryvaladzko** [comment]
При пустом массиве теперь будет выводиться null по нажатию кнопок. Будет добавлено в следующем коммите
