### ISSUE TITLE
2.1 JS замыкание на this

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-valery.valadzko#16]
Не совсем понятно необходимость этой переменной:
https://github.com/andrewQwer/iTechLab-17-valery.valadzko/blob/develop/2.1JS/js/main.js#L10
внутри ArrProc `this` доступна из любого метода и вызовы типа 
```
 this.createRandomArray = function () {
    self.arr = [];
```
выглядят странно

**Comment by valeryvaladzko** [comment]
Не знаю чем я тогда руководствовался, глупость полная.. Вроде это было сразу нужно, а затем я переделал и оставил как есть. Исправлено в следующем коммите.
