### ISSUE TITLE
2.1 JS - множественные операции с  DOM

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-valery.valadzko#17]
вызовы вида `document.getElementById('size')` можно было бы сделать 1 раз в конструкторе, присвоив их свойству класса ArrProc. А так на каждый метод ты дерагешь getElementById как будто он у тебя изменился с прошлого вызова.

**Comment by valeryvaladzko** [comment]
Так как убраны все операции с DOM из класса, то данная проблема решена. Повторные поиски элемента исключены запоминанием результата в переменной.
Будет в следующем коммите
