### ISSUE TITLE
2.1 JS - нет валидации на вводимые данные

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-valery.valadzko#18]
![image](https://user-images.githubusercontent.com/710513/29059647-47b79730-7c1f-11e7-9fc1-73c37e51b80b.png)

**Comment by valeryvaladzko** [comment]
Введена првоерка по ключу [^.0-9\s]. Так же исправлено корректное вычисление конечного массива при вводе множества пробелов между значениями.
