### ISSUE TITLE
2.2 - нажатие кнопки convert ни к чему не приводит

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-valery.valadzko#21]
Нажимаю кнопку Convert при открытии страницы и ничего не происходит. Должна вывестись сконвертированная дата в дефолтный выходной формат.
пример из задания: (“20130431”, “YYYYMMDD”) = 31 April 2013

**Comment by andrewQwer** [comment]
ТАк же ничего не происходит, если убрать значение из второго поля.

**Comment by valeryvaladzko** [comment]
Исправлено, будет в следующем коммите
