### ISSUE TITLE
2.2 нет валидации на корректность даты

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-valery.valadzko#23]
![image](https://user-images.githubusercontent.com/710513/29060450-7a651c72-7c22-11e7-8d2f-c5513bd1527a.png)
 при неверном исходном формате все корректно конвертируется, хотя месяц получается равен 28

**Comment by valeryvaladzko** [comment]
Добавлена валидация для варианта без введенного формата (по аналогии можно сделать и с другими.
