### ISSUE TITLE
2.4 - ui упрощен до невозможного

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-valery.valadzko#28]
можно было бы создать хотя бы визуальное подобие калькулятора
![image](https://user-images.githubusercontent.com/710513/29060642-5655c6b4-7c23-11e7-8781-58a0dc3d5eb8.png)
А если я хочу сделать операцию
5+6-8*3 ?

**Comment by valeryvaladzko** [comment]
Задание полностью переделано с цельной строкой, изменен алгоритм подсчета
