### ISSUE TITLE
Class naming

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-valery.valadzko#3]
Use either camel case naming, or use some separator like `-` or `_` for class names. 
Values like 'phonerighttext', 'phonetextsecond' are not readable.
Good examples of naming conventions you can find here: 
http://bdavidxyz.com/blog/how-to-name-css-classes/

**Comment by valeryvaladzko** [comment]
fixed
would be in next commit
(with BEM)
