### ISSUE TITLE
2.7 ui не информативен

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-valery.valadzko#33]
![image](https://user-images.githubusercontent.com/710513/29060945-86962e76-7c24-11e7-8284-ee876caea33b.png)
Не понятно, значение посчиталось заново, или вернулось из кэша. Хотелось бы больше информативности

**Comment by valeryvaladzko** [comment]
Добавлен комментарий к результату при получении его из кэша
