### ISSUE TITLE
#id selectors for classes

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-valery.valadzko#4]
It's not a good practice to use id selectors
`.phonerighttext #phonetextfirst`
Id selectors are allowed but usually they are grouping items, so the following nesting makes more sense that your one: 
`#phonetextfirst .phonerighttext`
I would avoid unreasonable #id selectors at all.

**Comment by valeryvaladzko** [comment]
fixed
would be in next commit
