### ISSUE TITLE
Arrow functions as event handlers

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-valery.valadzko#44]
Не рекомендуется использовать arrow functions в качестве обработчиков событий.
`<AddTicketsForm onSubmit={(values) => this.addTicket(values)}/>` 
https://facebook.github.io/react/docs/handling-events.html

**Comment by valeryvaladzko** [comment]
Исправлено, все обработчики событий  без стрелочных функций (теперь методы класса)
