### ISSUE TITLE
Action creators data

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-valery.valadzko#46]
```
export function addToCart(id, name, totalCount, price) {
    return {
        type: actions.ADD_TO_CART,
        id,
        name,
        totalCount,
        price
    }
}
```
все данные, связанные с экшеном должны лежать в свойстве `payload`
Т.е. экшн в минимальном исполнении состоит всего из 2 свойств: `type` и `payload`

**Comment by valeryvaladzko** [comment]
Исправлено, теперь action возвращает {type: XX_XXX, payload: { id, name, etc. }
