### ISSUE TITLE
вычисление props

### ISSUE THREAD

**Issue by andrewQwer** [andrewQwer/iTechLab-17-valery.valadzko#47]
`<CartItemsTitle count={totalCount === 0 ? null : totalCount} total={totalPrice === 0 ? null : '$'+totalPrice} name='blue'/>`

лучше подсчитать значения вне компонента
```
const countProp = totalCount === 0 ? null : totalCount;
<CartItemsTitle count={countProp} />
выглядит красивее и понятнее
```

**Comment by valeryvaladzko** [comment]
Исправлено, теперь никаких больших вычислений в фигурных скобках
